name: Feature Request
description: Propose a new feature for Rapina
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand your use case.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's your use case?
      placeholder: I'm trying to... but currently...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this feature to work.
      placeholder: |
        I'd like to be able to...

        Example API:
        ```rust
        #[get("/users")]
        async fn list_users(query: Query<Pagination>) -> Json<Vec<User>> {
            ...
        }
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches?

  - type: dropdown
    id: pillar
    attributes:
      label: Which pillar does this relate to?
      description: Rapina focuses on predictability, auditability, and security.
      options:
        - Predictability (conventions, DX)
        - Auditability (contracts, errors, observability)
        - Security (guardrails, validation)
        - Other / Not sure
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature
